
---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: EVPN VXLAN created
      condition: event.payload.event == "created" and event.payload.model == "l2vpntermination" and event.payload.data.l2vpn.type.value == "vxlan-evpn"
      action:
        run_job_template:
          organization: "Default"
          name: "Push EVPN configuration"
          job_args:
            extra_vars:
              SWITCH_NAME: "{{ event.payload.data.assigned_object.device.name }}"
              SERVICE_ID: "{{ event.payload.data.l2vpn.identifier }}"
              ACCESS_INTERFACE: "{{ event.payload.data.assigned_object.name }}"
              ACCESS_INTERFACE_URL: "{{ event.payload.data.assigned_object.url }}"
